// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/benpsk/go-starter/internal/web/components"

func HomePage(appName string, appURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.Layout(appName, appURL, "/", components.PageMeta{
			Title:       appName,
			Description: "Minimal Go starter with chi, pgx, templ, Tailwind, DaisyUI, htmx, and Chart.js.",
			Keywords:    "go starter,chi,pgx,templ,tailwind,daisyui,htmx,chartjs",
			Path:        "/",
			Type:        "website",
		}, HomeContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func HomeContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pb-6 pt-8 sm:pt-12\"><div class=\"grid gap-4 lg:grid-cols-[1.15fr_0.85fr]\"><div class=\"rounded-3xl border border-base-300/60 bg-base-100/90 p-7 shadow-xl\"><p class=\"badge badge-outline badge-primary\">Reusable stack starter</p><h1 class=\"mt-4 text-4xl font-black tracking-tight sm:text-5xl\">Go Starter</h1><p class=\"mt-4 max-w-2xl text-base-content/70\">A minimal template extracted from a production app structure. It includes routing, database wiring, migrations, templ pages, htmx navigation, and asset tooling.</p><div class=\"mt-6 flex flex-wrap gap-2\"><a class=\"btn btn-primary\" href=\"/about\">Open About</a> <a class=\"btn btn-outline\" href=\"/healthz\" hx-boost=\"false\">Health JSON</a></div><div class=\"mt-6 grid gap-3 sm:grid-cols-2\"><div class=\"rounded-2xl border border-base-300 bg-base-200/60 p-4\"><p class=\"text-xs uppercase tracking-widest text-base-content/50\">Backend</p><p class=\"mt-1 font-bold\">chi + pgx + migrate + dump</p></div><div class=\"rounded-2xl border border-base-300 bg-base-200/60 p-4\"><p class=\"text-xs uppercase tracking-widest text-base-content/50\">Frontend</p><p class=\"mt-1 font-bold\">templ + DaisyUI + htmx + Chart.js</p></div></div></div><div class=\"rounded-3xl border border-base-300/60 bg-base-100/90 p-6 shadow-lg\"><h2 class=\"text-lg font-bold\">Chart.js demo</h2><p class=\"mt-2 text-sm text-base-content/70\">The starter loads Chart.js and initializes this chart automatically.</p><div class=\"mt-4 rounded-2xl bg-base-200/50 p-3\"><canvas data-demo-chart height=\"220\"></canvas></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
